[package]
name = "bibcitex"
version = "0.6.0"
description = "A BibTeX citation tool"
authors = ["tangxiangong <tangxiangong@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
name = "bibcitex_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
arboard = "3"
biblatex = { version = "0.12", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
config = "0.15"
dirs = "6"
enigo = "0.6"
fs-err = "3"
image = "0.25"
once_cell = "1"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[target."cfg(target_os = \"macos\")".dependencies]
objc2-app-kit = "0.3.2"
[target."cfg(target_os = \"windows\")".dependencies]
windows = { version = "0.62.2", features = [
    "Win32_UI_Accessibility",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
