[package]
name = "nspanel"
version = "0.1.0"
authors = ["tangxiangong <tangxiangong@gmail.com>"]
edition = "2024"
description = "macOS panel for Dioxus"
license = "MIT"

[dependencies]
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3.1"
