[workspace]
members = [
    "bindings/csharp-generator",
    "bindings/generator",
    "crates/bibcitex-core",
    "crates/bibcitex-csharp",
    "crates/bibcitex-ffi",
    "crates/bibcitex-service",
    "crates/xpaste",
    "linux",
    "xtask",
]
default-members = ["crates/bibcitex-core"]
resolver = "3"

[workspace.package]
authors = ["tangxiangong <tangxiangong@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.7.3"

[workspace.dependencies]
arboard = "3"
ashpd = { version = "0.13", default-features = false, features = [
    "async-io",
    "global_shortcuts",
    "remote_desktop",
    "screencast",
] }
async-channel = "2"
base64 = "0.23"
bibcitex-core = { path = "crates/bibcitex-core" }
bibcitex-csharp = { path = "crates/bibcitex-csharp" }
bibcitex-service = { path = "crates/bibcitex-service" }
biblatex = { version = "0.12", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
config = "0.15"
dirs = "7"
dispatch2 = "0.3"
ed25519-dalek = "3"
enigo = "0.6"
flate2 = "1"
fs-err = "3"
futures-util = "0.3"
gpui-kit = "0.7.1"
hmac = "0.13"
image = { version = "0.25", default-features = false, features = [
    "png",
    "ico",
] }
interoptopus = "0.16"
interoptopus_csharp = "0.16"
ksni = { version = "0.3", default-features = false, features = ["async-io"] }
latex-rust = "2.1.1"
minisign = "0.10"
minisign-verify = "0.3"
objc2 = "0.6"
objc2-app-kit = "0.3"
quick-xml = "0.42"
raw-window-handle = "0.6"
rayon = "1"
reqwest = { version = "0.13", default-features = false, features = [
    "blocking",
    "rustls",
] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.11"
sha2 = "0.11"
smol = "2"
tar = "0.4"
tempfile = "3"
thiserror = "2"
unicode-normalization = "0.1"
uniffi = "0.32"
url = "2"
wayland-backend = { version = "0.3", features = ["client_system", "dlopen"] }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
windows = "0.62"
x11rb = { version = "0.14", features = ["xtest"] }
xpaste = { path = "crates/xpaste" }
