[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
hmac.workspace = true
reqwest.workspace = true
sha1.workspace = true
quick-xml.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
