[package]
name = "bibcitex-ffi"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Swift UniFFI bindings for BibCiTeX"

[dependencies]
bibcitex-service = { workspace = true }
uniffi = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
